# Pre-commit hooks - run: pre-commit install
# See https://pre-commit.com/
repos:
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: poetry run pytest tests/ -v -x
        language: system
        pass_filenames: false
        always_run: true
